version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=cris
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

